---
name: Checks # name that will appear in the Actions tab of the repo

on: [push] # event that will trigger the workflow

jobs:
  test-lint: # id of the job (can be anything)
    name: Test and Lint # name of the job (will appear in the Actions tab)
    
    runs-on: ubuntu-20.04
    
    steps: # steps runs sequentially
      - name: Login to Docker Hub # name of the step (can be anything)
        uses: docker/login-action@v1 # pre-made action to login to Docker Hub
        with: # credentials to login to Docker Hub
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout # name of the step (can be anything)
        uses: actions/checkout@v2 # pre-made action, allowing us to run scripts or other actions against our code
        
      - name: Test # name of the step (can be anything)
        id: test # id of the step (can be anything)
        run: docker-compose run --rm app sh -c "python manage.py test" # run the test command
        
      - name: Lint # name of the step (can be anything)
        id: lint # id of the step (can be anything)
        run: docker-compose run --rm app sh -c "flake8" # run the lint command 
        
      - name: Exit if test or lint fails # prevent the push if failure
        if: ${{ needs.test.result == 'failure' || needs.lint.result == 'failure' }}
        run: exit 1
